name: ms465-2026
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - scipy=1.10.1
  - matplotlib=3.10.8
  - hyperspy=2.3.0
  - scikit-learn=1.4.2
  - jupyter=7.5.2
  - pip
  - pip:
    - py4DSTEM=0.14.16
